### ISSUE TITLE
Untranslatable app

### ISSUE THREAD

**Issue by ghost** [ShaneQful/uRoku#4]
Hello,
Could you please make this app translatable?
Thanks for this great work!

**Comment by ShaneQful** [comment]
Sure I'll have a look at it

**Comment by ShaneQful** [comment]
9535eb455679b7015b3f4099b15c1ed73a1fae75

**Comment by ShaneQful** [comment]
@Anne017 you can add any languages you like in

https://github.com/ShaneQful/uRoku/blob/master/www/js/NLS.js

Just make sure the language code lines up with the one from Ubuntu Touch. I've added french as an example although my french is a bit rusty so feel free to correct any of it ... it's too bad Ubuntu Touch doesn't support Irish.

**Comment by ghost** [comment]
Thank you very much @ShaneQful, I really appreciate the time and efforts you spent on that topic.
I have made some proposals to improve the French translation.
Do not be ashamed of your French, it is quite good actually!

**Comment by ShaneQful** [comment]
No problem, thanks for the translation :+1:
